target:
  host: plexdev.azurecr.io
  repository: pcp
sources:
- repository: nginx
  tag: 1.14.2
- repository: open-policy-agent/gatekeeper
  host: quay.io
  tag: v3.1.0-beta.9
- repository: kubernetes-ingress-controller/nginx-ingress-controller
  host: quay.io
  tag: 0.32.0
- repository: coreos/kube-state-metrics
  host: quay.io
  tag: v1.9.5
- repository: coreos/prometheus-operator
  host: quay.io
  tag: v0.39.0
- repository: jimmidyson/configmap-reload
  tag: v0.3.0
- repository: coreos/prometheus-config-reloader
  host: quay.io
  tag: v0.39.0
- repository: consul
  tag: 1.7.2
- repository: prom/node-exporter
  tag: v0.18.1
- repository: grafana/promtail
  tag: v0.4.0
- repository: jettech/kube-webhook-certgen
  tag: v1.2.0
- repository: prom/alertmanager
  tag: v0.20.0
- repository: prom/prometheus
  tag: v2.18.1
