target:
  path: plexdev.azurecr.io/pcp
sources:
- path: nginx
  version: 1.14.0
- path: quay.io/open-policy-agent/gatekeeper
  version: v3.1.0-beta.9
- path: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  version: 0.32.0
- path: quay.io/coreos/kube-state-metrics
  version: v1.9.5
- path: quay.io/coreos/prometheus-operator
  version: v0.39.0
- path: jimmidyson/configmap-reload
  version: v0.3.0
- path: quay.io/coreos/prometheus-config-reloader
  version: v0.39.0
- path: consul
  version: 1.7.2
- path: prom/node-exporter
  version: v0.18.1
- path: grafana/promtail
  version: v0.4.0
- path: registry.twistlock.com/twistlock/defender
  version: defender_20_04_177
- path: jettech/kube-webhook-certgen
  version: v1.2.0
- path: prom/alertmanager
  version: v0.20.0
- path: prom/prometheus
  version: v2.18.1
